# Generated by Django 5.1.4 on 2024-12-07 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='posted_by',
        ),
    ]
